server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: products
    url: jdbc:h2:mem:products
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        web: DEBUG